[package]
name = "mymake"
version = "0.1.0"
authors = ["Fredrik Sandhei <fredrik.sandhei@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mmk_parser = { path = 'mmk_parser/' }
generator = { path = 'generator/' }
clap = "2.33.3"